name: Run tests

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9"]
        django-version: ["3.2", "4.0.4"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install pipenv
        run: pip install --user pipenv
        
      - name: Install all dependencies, including development ones
        run: pipenv sync --dev

      - name: Install Django
        run: pip install -q Django~=${{ matrix.django-version }}

      - name: Test
        run: pipenv run test
